# argus/core/interfaces/__init__.py

"""
Core interfaces for the Gemini SRE Agent system.

This package provides abstract base classes and interfaces that form
the foundation for all major components in the system.
"""

from .agent import (
    AgentCoordinator,
    AnalysisAgent,
    BaseAgent,
    RemediationAgent,
    TriageAgent,
)
from .base import (
    BaseComponent,
    ConfigurableComponent,
    MonitorableComponent,
    ProcessableComponent,
    StatefulComponent,
)
from .llm import (
    ChatModel,
    CompletionModel,
    EmbeddingModel,
    LLMManager,
    LLMModel,
    LLMProvider,
)
from .protocols import (  # Additional protocols
    AgentLike,
    Aggregator,
    Alertable,
    AsyncBatchProcessor,
    AsyncProcessable,
    BatchProcessor,
    Cacheable,
    CircuitBreaker,
    Configurable,
    CostTrackable,
    Deserializable,
    EventEmitter,
    EventListener,
    FallbackProvider,
    Filter,
    HealthCheckable,
    Identifiable,
    LoadBalancer,
    LockManager,
    Loggable,
    MetricsCollector,
    ModelLike,
    Observer,
    Pipeline,
    Processable,
    ProviderLike,
    RateLimited,
    RequestLike,
    ResourceManager,
    ResponseLike,
    Retryable,
    Scheduler,
    Serializable,
    Stateful,
    Streamable,
    Subject,
    Timestamped,
    TokenCountable,
    Transformer,
    Validatable,
    WorkflowOrchestrator,
    WorkflowStep,
    get_protocol_methods,
    implements_protocol,
    validate_protocol_implementation,
)

__all__ = [
    "AgentCoordinator",
    "AgentLike",
    "Aggregator",
    "Alertable",
    "AnalysisAgent",
    "AsyncBatchProcessor",
    "AsyncProcessable",
    # Agent interfaces
    "BaseAgent",
    # Base interfaces
    "BaseComponent",
    "BatchProcessor",
    "Cacheable",
    "ChatModel",
    "CircuitBreaker",
    "CompletionModel",
    "Configurable",
    "ConfigurableComponent",
    "CostTrackable",
    "Deserializable",
    "EmbeddingModel",
    "EventEmitter",
    "EventListener",
    "FallbackProvider",
    "Filter",
    "HealthCheckable",
    "Identifiable",
    "LLMManager",
    "LLMModel",
    # LLM interfaces
    "LLMProvider",
    "LoadBalancer",
    "LockManager",
    "Loggable",
    "MetricsCollector",
    "ModelLike",
    "MonitorableComponent",
    "Observer",
    "Pipeline",
    "Processable",
    "ProcessableComponent",
    "ProviderLike",
    "RateLimited",
    "RemediationAgent",
    "RequestLike",
    "ResourceManager",
    "ResponseLike",
    "Retryable",
    "Scheduler",
    # Protocol classes
    "Serializable",
    "Stateful",
    "StatefulComponent",
    "Streamable",
    "Subject",
    "Timestamped",
    "TokenCountable",
    "Transformer",
    "TriageAgent",
    "Validatable",
    "WorkflowOrchestrator",
    "WorkflowStep",
    "get_protocol_methods",
    # Protocol utilities
    "implements_protocol",
    "validate_protocol_implementation",
]
